FROM arm64v8/debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    meson \
    ninja-build \
    pkg-config \
    autoconf \
    automake \
    libtool \
    libsndfile1-dev \
    nlohmann-json3-dev \
    libmp3lame-dev \
    libmpg123-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
